name: '.NET Setup Action'
description: 'Checks out the repository and sets up .NET 7'
 
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Cache NuGet packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.nuget/packages
          **/*.lock.json
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: nuget-${{ runner.os }}-
 
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x


 